/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rgb_led.glb --types 
Author: mimivo (https://sketchfab.com/mimivo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rgb-led-7ee14ba4a6204e74a5d37169f342c785
Title: RGB LED
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
  }
  materials: {
    Glass_1: THREE.MeshPhysicalMaterial
    Metal_1: THREE.MeshPhysicalMaterial
  }
}

export function LEDModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/rgb_led.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Glass_1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Metal_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/rgb_led.glb')
